name: first_mobile_app_afg_network
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: ^0.20.2

  http: ^0.13.5
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
  flutter_lints: ^5.0.0
  google_fonts: ^4.0.4
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  path: ^1.9.0
  connectivity_plus: ^5.0.2
  url_launcher: ^6.1.10
  carousel_slider: 4.0.0




flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/


