name: first_mobile_app_afg_network
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  http: ^1.4.0
  connectivity_plus: ^5.0.2   # 👈 باید این‌جا باشد
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
  flutter_lints: ^6.0.0
  google_fonts: ^6.2.1
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  path: ^1.9.0

  url_launcher: ^6.1.10
  carousel_slider: ^5.1.1




flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/


